server:
  port: 8080


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka
    # 服务拉取
    registry-fetch-interval-seconds: 30

  instance:
    lease-renewal-interval-in-seconds: 10

spring:
  application:
    name: api-passenger
